export const TAGS_FILTER = [
  'Grão Direto',
  'tecnologia',
  'agronegócio',
  'CI/CD',
  'devops',
  'agilidade',
  'NoSQL',
  'banco de dados',
  'escalabilidade',
  'Kubernetes',
  'contêineres',
  'orquestração',
  'serverless',
  'segurança',
  'cloud',
  'DevOps',
  'colaboração',
  'times distribuídos',
  'frontend',
  'frameworks',
  'React',
  'inovação',
];
